### ISSUE TITLE
Hello,I have some questions about the program's input.

### ISSUE THREAD

**Issue by csq-123** [nassircassamo/IODMD_SOWFA#2]
Does the input to this program have to be exported by SOWFA?
What is the format of the data?
Looking forward to your reply.
Thank you very much.

**Comment by nassircassamo** [comment]
Hi James, 

I apologize for my late reply, these past few weeks have been chaotic.

I will answer here to your most recent e-mail and previous one.

1. What input parameters are you referring to exactly?
1.1 The majority of the settings is defined in the script Main.m. 
1.2. Other parameters concerning algorithms and in depth implementation must be changed within the functions themselves (preprocessdmdid, etc).

2. Data required for the script can be found here, with the folder name and structure that you just mentioned: https://drive.google.com/drive/folders/1_X4Aibg2-OM4qSwOxZ1yCTXlL-vTQPrn
That is correct, you do not need to run SOWFA, unless you wish to obtain a new different data set (program may not be suited to deal with different data sets coming from SOWFA).
You should change the path accordingly so that it matches the path in your computer where such folders are stored.

3. I believe the format of data will be clear as soon as you download the data set.

Good luck!
